---
- name: generate persistence TID
  set_fact:
    persistence_tokenId: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
- name: encrypt persistence TID
  set_fact:
    bcrypt_persistence_tokenId: "{{ lookup('vars', 'persistence_tokenId') | password_hash('bcrypt') | string | b64encode }}"

- name: generate lockers_core TID
  set_fact:
    lockers_core_tokenId: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
- name: encrypt lockers TID
  set_fact:
    bcrypt_lockers_core_tokenId: "{{ lookup('vars', 'lockers_core_tokenId') | password_hash('bcrypt') | string | b64encode }}"

- name: generate bootstrap TID
  set_fact:
    bootstrap_tokenId: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
- name: encrypt bootstrap TID
  set_fact:
    bcrypt_bootstrap_tokenId: "{{ lookup('vars', 'bootstrap_tokenId') | password_hash('bcrypt') | string | b64encode }}"

- name: generate core TID
  set_fact:
    core_tokenId: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
- name: encrypt core TID
  set_fact:
    bcrypt_core_tokenId: "{{ lookup('vars', 'core_tokenId') | password_hash('bcrypt') | string | b64encode }}"

- name: generate welcome_core TID
  set_fact:
    welcome_core_tokenId: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
- name: encrypt core TID
  set_fact:
    bcrypt_welcome_core_tokenId: "{{ lookup('vars', 'welcome_core_tokenId') | password_hash('bcrypt') | string | b64encode }}"

- name: create token secret
  docker_secret:
    name: token.json
    data: "{{ lookup('template', 'token.j2') | from_yaml | to_nice_json }}"
    data_is_b64: false
  ignore_errors: yes


- name: Create token service
  docker_swarm_service:
    name : token
    image: "{{ token_image }}"
    networks:
      - farbooking-network
    placement:
      constraints:
        - "node.hostname=={{ groups['docker_nodes'][1] }}"
    limits:
      cpus: '0.20'
      memory: 500M
    replicas: 1
    env:
      KEYSTORE_PASSWORD: "WmzI9pwvMuYQlORnftiS"
      KARAF_DEBUG: "TRUE"
      JAVA_DEBUG_PORT: "*:5005"
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 5005
        target_port: 5005

    secrets:
      - secret_name: token.json