---
- name: create welcome_core secret
  docker_secret:
    name: "welcome-core.json"
    data: "{{ lookup('template','welcome-core.j2') | from_yaml | to_nice_json }}"
    data_is_b64: no
  ignore_errors: yes

- name: create welcome_core service
  docker_swarm_service:
    name: welcome_core
    image: "{{ welcome_core_image }}"
    networks:
      - farbooking-network
    placement:
      constraints:
        - "node.hostname=={{ groups['docker_nodes'][1] }}"
    limits:
      cpus: '0.20'
      memory: 500M
    replicas: 1
    env:
      KEYSTORE_PASSWORD: "WmzI9pwvMuYQlORnftiS"
    secrets:
      - secret_name: welcome-core.json
