---
- name: Create /swarm/farbooking/ directory
  ansible.builtin.file:
    path: /swarm/farbooking/
    state: directory
    owner: 1001
    group: 1001
    mode: 0755

- name: Create farbooking persistence folder
  ansible.builtin.file:
    path: /swarm/farbooking/data
    state: directory
    owner: 1000
    group: 1000
    mode: 0755

- name: Create /swarm/farbooking/fileuploader/data directory
  ansible.builtin.file:
    path: /swarm/farbooking/fileuploader/data
    state: directory
    owner: 1001
    group: 1001
    mode: 0755

- name: create /swarm/farbooking/mongodb-primary/data directory
  ansible.builtin.file:
    path: /swarm/farbooking/mongodb-primary/data
    state: directory
    owner: 1001
    group: 0
    mode: 0755

- name: create /swarm/farbooking/nginx directory
  ansible.builtin.file:
    path: /swarm/farbooking/nginx
    state: directory
    owner: 1001
    group: 1001
    mode: 0755

- name: create /swarm/farbooking/postgresql/data directory
  ansible.builtin.file:
    path: /swarm/farbooking/postgresql/data
    state: directory
    owner: 1001
    group: 1001
    mode: 0755

- name: copy https.conf for nginx service
  copy:
    src: nginx/https.conf
    dest: /swarm/farbooking/nginx/https.conf
    owner: 1001
    group: 1001
    mode: 0755

- name: copy nginx.conf for nxing 
  copy:
    src: nginx/nginx.conf
    dest: /swarm/farbooking/nginx/nginx.conf
    owner: 1001
    group: 1001
    mode: 0755

- name: copy init.sh for psql
  copy:
    src: postgresql/init.sh
    dest: /swarm/farbooking/postgresql/init.sh
    owner: 1001
    group: 1001
    mode: 0755
# tasks file for dirsandfiles
